apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume-claim
  labels:
    app: influxdb
spec:
  volumeName: influxdb-volume
  accessModes:
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi

