apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  labels:
    app: mysql
spec:
  volumeName: mysql-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
