apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
