apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image : nginx-42
        imagePullPolicy: IfNotPresent
        env:
          - name: SSH_USER
            valueFrom:
              secretKeyRef:
                name: ssh-nginx
                key: username
          - name: SSH_PWD
            valueFrom:
              secretKeyRef:
                name: ssh-nginx
                key: password
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
