apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx_42
        imagePullPolicy: Never
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh-srcret
              key: username
        - name: SSH_PWD
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: password
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
