apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana_42
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
          envFrom:
          - secretRef:
              name: grafana-secret
