apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec: # Set Deployment
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-42
        imagePullPolicy: Never
        ports:
          - containerPort: 20
            hostPort: 20
          - containerPort: 21
            hostPort: 21
          - containerPort: 21100
            hostPort: 21100
          - containerPort: 21101
            hostPort: 21101
