apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      targetPort: 20
      name: ftp-data
      protocol: TCP
    - port: 21
      name: ftp
      targetPort: 21
      protocol: TCP
    - port: 21100
      name: passive0
      targetPort: 21100
      protocol: TCP
    - port: 21101
      name: passive1
      targetPort: 21101
      protocol: TCP
