NAME=ex01
SRCS=main.cpp Extra.cpp
FLAG=-Wall -Wextra -Werror -std=c++98

all : $(NAME)

$(NAME) : 
	clang++ $(FLAG) -o $(NAME) $(SRCS)

clean : 
	rm -rf $(SRCS.c=.o)
	
fclean: clean 
	rm -rf $(NAME)

re : fclean all
